Repository Automattic/page-optimize, pull requests merged in 2020-03, with the labels that each got.

#33 No need to queue cache cleanup if not using cache
  page-optimize.php
  readme.txt
Labels: enhancement

#34 Add basis for unit testing
  .editorconfig
  .gitignore
  .phpcs.xml.dist
  .travis.yml
  bin/install-wp-tests.sh
  composer.json
  composer.lock
  dependency-path-mapping.php
  phpunit.xml.dist
  tests/bootstrap.php
  tests/data/url-to-file-mapping/content/exists
  tests/data/url-to-file-mapping/content/plugins/exists
  tests/data/url-to-file-mapping/plugins/exists
  tests/data/url-to-file-mapping/site/content/exists
  tests/data/url-to-file-mapping/site/content/plugins/exists
  tests/data/url-to-file-mapping/site/exists
  tests/data/url-to-file-mapping/site/plugins/exists
  tests/test_URL_to_file_mapping.php
Labels: work in progress

#35 Fix resolution of sources based on abspath
  dependency-path-mapping.php
  tests/test_URL_to_file_mapping.php
Labels: bug
