Repository Automattic/page-optimize, pull requests merged in 2020-02, with the labels that each got.

#1 Add loading mode for concat JS
  concat-js.php
Labels: enhancement

#3 Add exclusion list, multiple load modes, update UI copy
  concat-js.php
  page-optimize.php
  settings.php
Labels: enhancement

#6 Add readme so the plugin can be published
  page-optimize.php
  readme.txt
Labels: documentation

#7 Re-add local caching and make it opt-in
  service.php
Labels: enhancement

#10 Concat all CSS into a single file, and load early.
  concat-css.php
  concat-js.php
  cssmin/Colors.php
  cssmin/Minifier.php
  cssmin/Utils.php
  page-optimize.php
  settings.php
Labels: enhancement

#11 Use exclude list defaults for both page render and admin settings
  page-optimize.php
  settings.php
Labels: bug

#13 Improve settings page appearance
  settings.php
Labels: enhancement

#16 Bail if we're in customizer
  concat-js.php
  page-optimize.php
  readme.txt
Labels: bug

#15 Cache cleanup with WP Cron
  page-optimize.php
  readme.txt
  service.php
Labels: enhancement

#18 Address plugin directory feedback
  concat-css.php
  concat-js.php
  dependency-path-mapping.php
  page-optimize.php
  readme.txt
  service.php
  utils.php
Labels: bug

#21 Extract duplicate code to utils
  concat-css.php
  concat-js.php
  page-optimize.php
  readme.txt
  utils.php
Labels: enhancement

#24 Update concat service to run without loading WordPress
  concat-css.php
  concat-js.php
  dependency-path-mapping.php
  page-optimize.php
  readme.txt
  service.php
  utils.php
Labels: enhancement

#25 Don't concat if we're inside Divi Front End Builder
  page-optimize.php
Labels: enhancement

#27 Limit cached headers
  page-optimize.php
  readme.txt
  service.php
Labels: bug

#30 Add script to deploy to .org plugin directory
  .gitignore
  bin/deploy-to-plugin-directory.sh
  readme.txt
Labels: enhancement, work in progress

#31 Fix hardcoded tag in deploy script
  bin/deploy-to-plugin-directory.sh
Labels: bug

#29 Don't `gzip` in PHP, and add constant for CSS minification
  page-optimize.php
  readme.txt
  service.php
Labels: enhancement

#32 Fix minor readme issues
  readme.txt
Labels: bug
